// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseLoading: typeof import('./src/components/BaseLoading.vue')['default']
    Form: typeof import('./src/components/Pokedex/Form.vue')['default']
    Index: typeof import('./src/components/Footer/Index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Screen: typeof import('./src/components/Pokedex/Screen.vue')['default']
    ScreenTypes: typeof import('./src/components/Pokedex/ScreenTypes.vue')['default']
    Stat: typeof import('./src/components/Pokedex/Stat.vue')['default']
    Stats: typeof import('./src/components/Pokedex/Stats.vue')['default']
    VAppBar: typeof import('vuetify/lib')['VAppBar']
    VAppBarNavIcon: typeof import('vuetify/lib')['VAppBarNavIcon']
    VBtn: typeof import('vuetify/lib')['VBtn']
    VCard: typeof import('vuetify/lib')['VCard']
    VCardActions: typeof import('vuetify/lib')['VCardActions']
    VCardText: typeof import('vuetify/lib')['VCardText']
    VCardTitle: typeof import('vuetify/lib')['VCardTitle']
    VChip: typeof import('vuetify/lib')['VChip']
    VChipGroup: typeof import('vuetify/lib')['VChipGroup']
    VCol: typeof import('vuetify/lib')['VCol']
    VDivider: typeof import('vuetify/lib')['VDivider']
    VFooter: typeof import('vuetify/lib')['VFooter']
    VIcon: typeof import('vuetify/lib')['VIcon']
    VImg: typeof import('vuetify/lib')['VImg']
    VListItem: typeof import('vuetify/lib')['VListItem']
    VListItemAvatar: typeof import('vuetify/lib')['VListItemAvatar']
    VListItemContent: typeof import('vuetify/lib')['VListItemContent']
    VListItemSubtitle: typeof import('vuetify/lib')['VListItemSubtitle']
    VListItemTitle: typeof import('vuetify/lib')['VListItemTitle']
    VProgressCircular: typeof import('vuetify/lib')['VProgressCircular']
    VProgressLinear: typeof import('vuetify/lib')['VProgressLinear']
    VRating: typeof import('vuetify/lib')['VRating']
    VRow: typeof import('vuetify/lib')['VRow']
    VSpacer: typeof import('vuetify/lib')['VSpacer']
    VToolbarTitle: typeof import('vuetify/lib')['VToolbarTitle']
  }
}

export {}
